- nerd-icons.el
* nerd-icons.el (nerd-icons-extension-icon-alist): Add entry for '.sty' extension which is a LaTeX package.
(nerd-icons-mode-icon-alist): Add entry for doctex-mode.
> Improve support for various LaTeX modes

- nerd-icons.el
- For Doc View
- For two different Calibre packages (https://melpa.org/#/calibredb and https://elpa.gnu.org/packages/calibre.html)
- For OSM mode
> Add icons for some document related modes

- nerd-icons.el
For
- Telega (Telegram client)
- Mastodon
- Missing Elfeed mode icon
> Icons for some social network related modes

- nerd-icons.el
- cljc now uses the half filled logo
- Add icon for cljs files
- Support clojurescript and clojurec-ts modes
- cljs icon color is now lyellow
> Improve clojure support

- nerd-icons.el
[Expect](https://www.man7.org/linux/man-pages/man1/expect.1.html) is a program that "talks" to other interactive programs according to a script. Expectk is a mixture of Expect and Tk.  It behaves just like Expect and Tk's wish. Expect can also be used directly in C or C++ (that is, without Tcl).
Emacs already opens expect files in Tcl-mode by default for font lock. 
I noticed, that unlick TCL files I open , expect files didn't have an icon attached to it on the modeline. This PR aims to solve it.
> Use the same tcl icon for expect scripts

- nerd-icons.el
Since gpg is supported, I thought I'd add support for the popular password managers keepass / keepassxc
> key icon for keepass databases

- nerd-icons.el
zst is another one of these compression formats.
It's the one I use most often
> add support for .zst

- nerd-icons.el
The context here is I have some code which does completion on relative paths so stuff like `../../ab/cd.el` etc, because of  `("^\\." nerd-icons-octicon "nf-oct-gear")` in `nerd-icons-regexp-icon-alist` all relative path end up with the gear icon. As far as I can tell, the regexps in that alist seemed designed to match the non-directory part of filename and not the whole path and hence this patch.
> Only match the non-directory part of file name

- nerd-icons.el
When using `nerd-icons-set-font`, I found that some icons not setup by this function.
See: https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/test-fonts.sh
> Fix nerd icons charset range

- nerd-icons.el
Note that this requires Nerd Fonts 3.2.0 updates available in #76 as the Ada icon was just recently added.
> Add support for Ada and GNAT Project files and modes.

- nerd-icons.el
Add mode icon for [Eat](https://codeberg.org/akib/emacs-eat)
> chore: add icon for eat-mode

- nerd-icons.el
Add an icon for the Dart tree-sitter mode found [here](https://github.com/50ways2sayhard/dart-ts-mode).
> feat: add dart-ts-mode icon

- nerd-icons.el
Add an icon for `go-work-ts-mode`, a mode for working with Go workspace files introduced by yours truly in https://github.com/emacs-mirror/emacs/commit/aade1b707c6b4932ed023f387d49324c6a7123eb.
> feat: add go-work-ts-mode icon

- nerd-icons.el
This improves support for file types related to Apple platform development:
- Adjust Swift icon color: the official logo is a red-orange, not green. While this can vary by the user's theme, `nerd-icons-lred` is the closest built-in value.
- Recognize `swift-ts-mode` as a Swift major mode
- Add file extensions:
- "plist" (Apple Property List)
-  "nib" and "xib" (Apple Interface Builder)
- "idekeybindings" (Xcode keybindings)
- Add file regexes for common dev tools based on Ruby: Fastlane, Danger, and Cocoapods
> Add/update values for Apple development files

- nerd-icons.el
- EXWM (GNU ELPA)
- Lisp Data (built-in)
- Proced (built-in)
- Bluetooth (GNU ELPA)
- Disk Usage (GNU ELPA)
- Awk (built-in)
- Ement (GNU ELPA)
- Diff/Patch by extension
- COPYING as an alias of LICENSE
- LICENSE-* (to support LICENSE-MIT, LICENSE-APACHE, etc.)
- Use the Rust logo for for Cargo.lock and Cargo.toml
I've broken these changes up into individual commits and I'm happy to remove some and/or make separate PRs if desired.
> Add icons for several modes/file types

- nerd-icons.el
> add an icon for the old kdb keepass database format

- nerd-icons.el
Use the Terraform icon for `.tfbackend` files
See https://developer.hashicorp.com/terraform/language/backend#file
> feat(terraform): add `.tfbackend` icon

- nerd-icons.el
With dired I found that some python files named merge_*.py were displayed with the vc branch or merge icon instead of the python icon. I propose to change the order of the file name matching checks to first check the file extension, then check the file basename. IMHO the file extension should take precedence over the file basename.
> Change order of file name to icon-alist checks

- nerd-icons.el
- Added "nu" file type with associated Nerd Font icon and green face
- Added `nushell-mode` and `nushell-ts-mode` with corresponding icons and styling - Fixed inconsistent alignment in icon definitions for better readability
> feat: Add support for Nushell file and mode icons

- nerd-icons.el
Related https://github.com/doomemacs/doomemacs/issues/8517
> fix: only show the Gopher icon for exact matches

- nerd-icons.el
- feat: Add entries for NEWS files and change COPYING to use copyright icon
- fix: Also recognize LICENSE files with    extension, better matching icon
- feat: Add entries for INSTALL files
- feat: Add types for rpm-spec and changes files
- feat: Add types for patch and diff files
- feat: Add types for cpio and obscpio files
- fix: Also recognize GNUMakefile and Makefiles with    extension as a Makefile
- feat: Recognize autotools related files
- fix: README files have varying suffixes
E.g. as in README-maintainer-mode
- Fix: Recognize CMake related directories/files correctly
- feat: Recognize object files
- feat: Also recognize other GNU related documentation files
- feat: Recognize m4 related modes
> Recognize more file types and modes
